import React,{useEffect,useRef} from 'react';
import {Moon,Sun,X,Target} from 'lucide-react';
export const API=import.meta.env.VITE_API_URL||(import.meta.env.DEV?'':'http://localhost:8000');
export const EMPTY={network:{nodes:[],edges:[]},documents:[],analytics:[],leads:[],overview:{nodes:0,edges:0,reports:0,leads:0}};
export const COLORS={Person:'#2453d4',Organization:'#207d91',Phone:'#138468',Account:'#b26419',Vehicle:'#7b64b8',Location:'#7a889c',IMEI:'#138468',Event:'#7a889c',Date:'#7a889c',Time:'#7a889c',Money:'#b26419'};
export function readSetting(key,fallback){try{return localStorage.getItem(key)||fallback;}catch{return fallback;}}
export async function api(path,options={}){let r;try{r=await fetch(API+path,options);}catch(e){if(e.name==='AbortError')throw e;throw new Error('Cannot reach the backend. Start the API and check its address.');}let body;try{body=await r.json();}catch{throw new Error('The server returned an unreadable response.');}if(!r.ok){const d=body.detail;throw new Error(typeof d==='string'?d:d?.message||(Array.isArray(d)?d.map(x=>x.msg).join('; '):'The request could not be completed.'));}return body;}
export function Logo(){return <div className="brand"><svg viewBox="0 0 40 46" aria-hidden="true"><path d="M20 2 37 12v22L20 44 3 34V12Z"/><path d="M20 9v28M20 17 10 27m10-10 10 10M10 27h20"/><circle cx="20" cy="10" r="3"/><circle cx="20" cy="21" r="3"/><circle cx="10" cy="28" r="3"/><circle cx="30" cy="28" r="3"/></svg><span><strong>SENTINELGRAPH</strong><small>CRIMINAL NETWORK INTELLIGENCE</small></span></div>;}
export function ThemeButton({theme,toggle}){return <button className="icon-button" onClick={toggle} aria-label={theme==='dark'?'Switch to light mode':'Switch to dark mode'}>{theme==='dark'?<Sun size={17}/>:<Moon size={17}/>}</button>;}
export function Intro({eyebrow,title,description,badge}){return <div className="page-intro"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2><p>{description}</p></div>{badge&&<span className="classification mono">{badge}</span>}</div>;}
export function Empty({title,description,icon:Icon=Target}){return <div className="empty-state"><Icon size={23}/><strong>{title}</strong><p>{description}</p></div>;}
export function Modal({title,close,children}){const ref=useRef(null),closeRef=useRef(close);closeRef.current=close;useEffect(()=>{const before=document.activeElement;ref.current?.querySelector('input,button')?.focus();const onKey=e=>{if(e.key==='Escape')closeRef.current();if(e.key==='Tab'){const fields=[...ref.current.querySelectorAll('button,input,select,textarea,a[href]')].filter(x=>!x.disabled);const first=fields[0],last=fields.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',onKey);return()=>{document.removeEventListener('keydown',onKey);before?.focus();};},[]);return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close();}}><section ref={ref} role="dialog" aria-modal="true" aria-label={title} className="modal panel"><div className="modal-head"><h2>{title}</h2><button className="icon-button" onClick={close} aria-label="Close dialog"><X size={16}/></button></div>{children}</section></div>;}
